spring.application.name=SpringOAuth2

server.port = 8082

spring.profiles.include=oauth

#H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:~/oauth
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.settings.web-allow-others=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

#\uC138\uC158 \uC800\uC7A5\uC18C
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always